###################################
#### Quarto configuration file ####
###################################

## this file sets options that apply to all your .qmd files

project:
    # make quarto interpret paths relative to the project root
    # (default is relative to the qmd file's location)
    execute-dir: project 
    # render everything in the ./out directory
    output-dir: out

editor:
    # useful when .qmd files take long to render
    render-on-save: false

author: "Alex Lambda"
bibliography: assets/references.bib

#### rendering options ---------------------------
## we have configured sane defaults for 3 formats: 
# pdf, html, gfm (Github markdown, for pretty rendering on GitHub)
## by default, we render Quarto documents as html
## to use another format, comment out the formats you don't want 
## and uncomment the format you want to use

## options that apply to all formats
fig-width: 6.2 # makes figures full-width in A4 page with 1in margins
lof: true # include a list of figures
lot: true # include a list of tables
number-sections: true # all sections are numbered
format:
    pdf:
        # set the document margins to 1in
        geometry:
            - top=1in
            - bottom=1in
            - left=1in
            - right=1in
    # html:
        ## ensures that html files are self-contained
        ## this means you can share just the .html file and it will render properly
        ## see https://quarto.org/docs/output-formats/html-basics.html#self-contained
        # embed-resources: true
    # gfm: default

knitr:
    opts_chunk:
        # hide all code blocks by default
        echo: false
        R.options:
            # when printing a table, NA values are hiden
            knitr.kable.NA: ""
            # hides dplyr info message when using summarize()
            dplyr.summarise.inform: false

